import json
import math
from pathlib import Path

import numpy as np
import pytest

from touchstone import BinderDesign, BondValenceVerifier
from touchstone.core import CoordinationSite, oxidation_state
from touchstone.geometry.bond_valence import TOLERANCE_KEYS, load_params

OCT = np.array([[1, 0, 0], [-1, 0, 0], [0, 1, 0], [0, -1, 0], [0, 0, 1], [0, 0, -1]], float)
FIX = Path(__file__).parent / "fixtures"


def sphere(n: int) -> np.ndarray:
    """n directions on a golden-spiral sphere — BVS is distance-only, so directions just need to be
    distinct and support any coordination number (real sites reach CN 7)."""
    i = np.arange(n) + 0.5
    phi = np.arccos(1 - 2 * i / n)
    theta = np.pi * (1 + 5**0.5) * i
    return np.column_stack([np.cos(theta) * np.sin(phi), np.sin(theta) * np.sin(phi), np.cos(phi)])


def site_from_bonds(metal: str, bonds: list[tuple[str, float]]) -> CoordinationSite:
    elems = tuple(e for e, _ in bonds)
    xyz = sphere(len(bonds)) * np.array([d for _, d in bonds])[:, None]
    return CoordinationSite(metal, np.zeros(3), xyz, elems)


def design(metal: str = "Ni2+", bond: float = 2.06, n: int = 6, elem: str = "O") -> BinderDesign:
    site = CoordinationSite(metal, np.zeros(3), OCT[:n] * bond, (elem,) * n)
    return BinderDesign("SEQ", site, generator="test", generator_confidence=0.5)


def valence_satisfying_bond(metal: str, elem: str, n: int) -> float:
    """The M–donor distance at which n bonds sum to the formal valence under the shipped params —
    i.e. d such that n·exp((R0−d)/b) = valence. Derived from the params so the tests track a refit."""
    p = load_params()
    entry = p["metals"][metal]
    return entry[elem] - p["b"] * math.log(oxidation_state(metal) / n)


@pytest.fixture
def verifier() -> BondValenceVerifier:
    return BondValenceVerifier()


class TestBondValenceVerifier:
    def test_charge_recovering_site_is_trusted(self, verifier):
        # a site at the protein-domain valence-satisfying geometry trusts (2.30 Å for 6 Ni–O, vs the
        # small-molecule 2.06 Å the old params assumed — the recalibration is exactly this shift)
        bond = valence_satisfying_bond("Ni2+", "O", 6)
        assert bond > 2.25  # protein-domain, not the ~2.06 Å small-molecule value
        v = verifier.verify(design(bond=bond))
        assert v.trust and not v.ood and v.score > 0.8

    def test_egregiously_over_bonded_site_defers(self, verifier):
        # crushed bonds overshoot the valence sum for every metal — over-bonding stays crisp even
        # though the protein-domain tolerances are wide (under-bonding detection is metal-dependent,
        # which is the honest weakness the calibration test below pins down)
        v = verifier.verify(design(bond=1.7))
        assert v.ood and not v.trust

    def test_unknown_metal_raises(self, verifier):
        with pytest.raises(KeyError):
            verifier.verify(design(metal="Au3+"))

    def test_empty_site_defers_with_finite_score(self, verifier):
        empty = BinderDesign(
            "SEQ", CoordinationSite("Ni2+", np.zeros(3), np.empty((0, 3)), ()),
            generator="test", generator_confidence=0.5,
        )
        v = verifier.verify(empty)
        assert v.score == 0.0 and v.ood and not v.trust

    def test_unparameterized_donor_defers(self, verifier):
        # P is not in the R0 table — must defer, not silently undercount the BVS. Also guards that the
        # tolerance/domain metadata keys are not mistaken for donor elements.
        v = verifier.verify(design(elem="P"))
        assert v.ood and not v.trust and "not parameterized" in v.reason


class TestBvsCalibration:
    """The params that ship, checked against real metalloprotein sites (tests/fixtures/
    metalpdb_bvs_sites.json, element + distance, regenerated by scripts/build_bvs_fixture.py through
    the builder's own filters). In-sample — the fixture is a subsample of the pull the params were fit
    on — so the ~10% defer rate is largely true by construction; its teeth are in the *reversion*
    direction: the old small-molecule R0 deferred 64% of real Ni²⁺ sites, and a BVS tier that rejects
    real biochemistry can only collapse the consensus on good designs. See
    docs/experiments/2026-07-17-bond-valence-wrong-domain.md."""

    @staticmethod
    @pytest.fixture(scope="class")
    def real_sites() -> dict[str, list]:
        raw = json.loads((FIX / "metalpdb_bvs_sites.json").read_text())
        return {m: [[(e, d) for e, d in s] for s in sites] for m, sites in raw.items()}

    def defer_rate(self, metal: str, sites: list, verifier: BondValenceVerifier) -> float:
        oods = sum(
            verifier.verify(BinderDesign("", site_from_bonds(metal, b), generator="t", generator_confidence=0.0)).ood
            for b in sites
        )
        return oods / len(sites)

    @pytest.mark.parametrize("metal", ["Ni2+", "Cu2+", "Co2+"])
    def test_recalibrated_params_do_not_reject_real_sites(self, metal, real_sites):
        # BVS should very rarely *defer* a real site (a defer collapses the whole consensus); weak is
        # fine — BVS is a weak filter in this domain. The 90th-percentile ood_tol targets ~10% defer.
        rate = self.defer_rate(metal, real_sites[metal], BondValenceVerifier())
        assert rate <= 0.15, f"BVS defers {rate:.0%} of real {metal} protein sites"

    def test_small_molecule_params_would_reject_real_sites(self, real_sites):
        # the regression, as a test: the old Brese & O'Keeffe Ni R0 defers most real Ni sites. If this
        # ever stops failing, the shipped params drifted back to the small-molecule domain.
        small_mol = {"b": 0.37, "metals": {"Ni2+": {"N": 1.647, "O": 1.654, "S": 2.04}}}
        v = BondValenceVerifier(params=small_mol)  # ctor tol fallback 0.4/0.8 = the old behaviour
        assert self.defer_rate("Ni2+", real_sites["Ni2+"], v) > 0.5

    def test_shipped_params_are_protein_domain(self):
        for metal, entry in load_params()["metals"].items():
            assert "metalloprotein" in entry.get("domain", ""), f"{metal} is not protein-domain"
            assert {"trust_tol", "ood_tol"} <= set(entry)  # data owns the tolerance
            assert set(TOLERANCE_KEYS) & set(entry)  # metadata keys present and excluded from R0
